/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/fairwindsops/photon/pkg/types/snapshotgroup/v1"
	scheme "github.com/fairwindsops/photon/pkg/types/snapshotgroup/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SnapshotGroupsGetter has a method to return a SnapshotGroupInterface.
// A group's client should implement this interface.
type SnapshotGroupsGetter interface {
	SnapshotGroups(namespace string) SnapshotGroupInterface
}

// SnapshotGroupInterface has methods to work with SnapshotGroup resources.
type SnapshotGroupInterface interface {
	Create(ctx context.Context, snapshotGroup *v1.SnapshotGroup, opts metav1.CreateOptions) (*v1.SnapshotGroup, error)
	Update(ctx context.Context, snapshotGroup *v1.SnapshotGroup, opts metav1.UpdateOptions) (*v1.SnapshotGroup, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.SnapshotGroup, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SnapshotGroupList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SnapshotGroup, err error)
	SnapshotGroupExpansion
}

// snapshotGroups implements SnapshotGroupInterface
type snapshotGroups struct {
	client rest.Interface
	ns     string
}

// newSnapshotGroups returns a SnapshotGroups
func newSnapshotGroups(c *SnapshotgroupV1Client, namespace string) *snapshotGroups {
	return &snapshotGroups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the snapshotGroup, and returns the corresponding snapshotGroup object, and an error if there is any.
func (c *snapshotGroups) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SnapshotGroup, err error) {
	result = &v1.SnapshotGroup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("snapshotgroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SnapshotGroups that match those selectors.
func (c *snapshotGroups) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SnapshotGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SnapshotGroupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("snapshotgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested snapshotGroups.
func (c *snapshotGroups) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("snapshotgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a snapshotGroup and creates it.  Returns the server's representation of the snapshotGroup, and an error, if there is any.
func (c *snapshotGroups) Create(ctx context.Context, snapshotGroup *v1.SnapshotGroup, opts metav1.CreateOptions) (result *v1.SnapshotGroup, err error) {
	result = &v1.SnapshotGroup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("snapshotgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(snapshotGroup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a snapshotGroup and updates it. Returns the server's representation of the snapshotGroup, and an error, if there is any.
func (c *snapshotGroups) Update(ctx context.Context, snapshotGroup *v1.SnapshotGroup, opts metav1.UpdateOptions) (result *v1.SnapshotGroup, err error) {
	result = &v1.SnapshotGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("snapshotgroups").
		Name(snapshotGroup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(snapshotGroup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the snapshotGroup and deletes it. Returns an error if one occurs.
func (c *snapshotGroups) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("snapshotgroups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *snapshotGroups) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("snapshotgroups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched snapshotGroup.
func (c *snapshotGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SnapshotGroup, err error) {
	result = &v1.SnapshotGroup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("snapshotgroups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
