/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	snapshotgroupv1 "github.com/fairwindsops/gemini/pkg/types/snapshotgroup/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSnapshotGroups implements SnapshotGroupInterface
type FakeSnapshotGroups struct {
	Fake *FakeSnapshotgroupV1
	ns   string
}

var snapshotgroupsResource = schema.GroupVersionResource{Group: "snapshotgroup", Version: "v1", Resource: "snapshotgroups"}

var snapshotgroupsKind = schema.GroupVersionKind{Group: "snapshotgroup", Version: "v1", Kind: "SnapshotGroup"}

// Get takes name of the snapshotGroup, and returns the corresponding snapshotGroup object, and an error if there is any.
func (c *FakeSnapshotGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *snapshotgroupv1.SnapshotGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(snapshotgroupsResource, c.ns, name), &snapshotgroupv1.SnapshotGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*snapshotgroupv1.SnapshotGroup), err
}

// List takes label and field selectors, and returns the list of SnapshotGroups that match those selectors.
func (c *FakeSnapshotGroups) List(ctx context.Context, opts v1.ListOptions) (result *snapshotgroupv1.SnapshotGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(snapshotgroupsResource, snapshotgroupsKind, c.ns, opts), &snapshotgroupv1.SnapshotGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &snapshotgroupv1.SnapshotGroupList{ListMeta: obj.(*snapshotgroupv1.SnapshotGroupList).ListMeta}
	for _, item := range obj.(*snapshotgroupv1.SnapshotGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested snapshotGroups.
func (c *FakeSnapshotGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(snapshotgroupsResource, c.ns, opts))

}

// Create takes the representation of a snapshotGroup and creates it.  Returns the server's representation of the snapshotGroup, and an error, if there is any.
func (c *FakeSnapshotGroups) Create(ctx context.Context, snapshotGroup *snapshotgroupv1.SnapshotGroup, opts v1.CreateOptions) (result *snapshotgroupv1.SnapshotGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(snapshotgroupsResource, c.ns, snapshotGroup), &snapshotgroupv1.SnapshotGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*snapshotgroupv1.SnapshotGroup), err
}

// Update takes the representation of a snapshotGroup and updates it. Returns the server's representation of the snapshotGroup, and an error, if there is any.
func (c *FakeSnapshotGroups) Update(ctx context.Context, snapshotGroup *snapshotgroupv1.SnapshotGroup, opts v1.UpdateOptions) (result *snapshotgroupv1.SnapshotGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(snapshotgroupsResource, c.ns, snapshotGroup), &snapshotgroupv1.SnapshotGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*snapshotgroupv1.SnapshotGroup), err
}

// Delete takes name of the snapshotGroup and deletes it. Returns an error if one occurs.
func (c *FakeSnapshotGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(snapshotgroupsResource, c.ns, name), &snapshotgroupv1.SnapshotGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSnapshotGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(snapshotgroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &snapshotgroupv1.SnapshotGroupList{})
	return err
}

// Patch applies the patch and returns the patched snapshotGroup.
func (c *FakeSnapshotGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *snapshotgroupv1.SnapshotGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(snapshotgroupsResource, c.ns, name, pt, data, subresources...), &snapshotgroupv1.SnapshotGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*snapshotgroupv1.SnapshotGroup), err
}
